### ISSUE TITLE
twillio vs clickatell vs tollfree

### ISSUE THREAD

**Issue by OrkoHunter** [gauravrpjain/Msg-Me-CDC#1]
twillio might be an easy choice but surely a little expensive one. I have used [clickatell](www.clickatell.com) which costs half as much as twillio and has an easy to use API too.
Further, there's [pilvo](https://www.plivo.com/twilio-alternative/) which was created as an alternative to twilio.
Still, we **need** to have a free API and a toll free number.

Good work, by the way.

**Comment by gauravrpjain** [comment]
Thanks. Any suggestions and improvements are welcome.
Clickatell costs around 1Re while Twilio costs 60 paise. While pilvo does seems interesting, I have not tried it yet. Whatever we try there is still a need to have a free API.

**Comment by OrkoHunter** [comment]
Oh, my bad. Clickatell allows 3 messages in around 1 "credit" which costs around Rs.3.
